import Head from "next/head";
import { useEffect, useState } from "react";
import getHelloWorld from "@/service/helloService";
import { StatusMessage } from "@/types";
import Header from "@/components/header";

const Hello: React.FC = () => {
  const [message, setMessage] = useState<StatusMessage>();

  const getMessage = async () => {
    try {
      const response = await getHelloWorld();
      const message = await response.json();
      setMessage(message);
    } catch (error) {
      setMessage({ id: 0, message: "Server Error" });
    }
  };

  useEffect(() => {
    getMessage();
  }, []);

  return (
    <>
      <Head>
        <title>Hello World App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <header className=" bg-slate-700 flex flex-col items-center">
        <h1 className=" text-3xl text-gray-300">Hello World App</h1>
        <nav className="text-white mt-4 mb-2 text-xl">Home</nav>
      </header> */}
      <Header />
      <main>
        <p className="text-4xl flex justify-center mt-20 ">
          {message?.message}
        </p>
      </main>
    </>
  );
};
export default Hello;
